### ISSUE TITLE
Toggling between two icons

### ISSUE THREAD

**Issue by ksherman** [FortAwesome/vue-fontawesome#30]
Hiya!

So I am working on a sortable table and using the sort/sort-up/sort-down icons

![dec-21-2017 13-41-04](https://user-images.githubusercontent.com/2822402/34272108-9e9872d2-e654-11e7-945a-28eac65fa3ea.gif)

But try as I might, I can't get the icon components to change after the first instance. Almost like the DOM node is being rendered but not cleared when the `icon` should change.

in the template:
```
  <icon icon="sort" v-if="sort.segment !== 'completed_at'"></icon>
  <icon :icon="sortIconDirection" v-else></icon>
```
and I have a computed value:
```
    sortIconDirection() {
      return this.sort.direction === 'asc' ? 'sort-up' : 'sort-down';
    },
```

And I can see the computed value correctly toggling in state, but the icon doesn't switch out. I've also tried adding another `icon` component with a set of v-if/else-if conditions and I can't get it to quite work. (BTW, `icon` is just what I named the imported `vue-fontawesome` component as, migrating over from `Justineo/vue-awesome`)

I hope this makes sense! I've been up for a long time ha. If needed, I can try to build a reduced test case if you're unable to reproduce.

Thanks!

**Comment by OriginalEXE** [comment]
Hmm, I am seeing the same issue, I found that adding `:key="JSON.stringify(sortIconDirection)"` to your icon element solves this, but I am interested in understanding why it's needed at all.

**Comment by ksherman** [comment]
Interesting! I'll give that a shot. I was literally thinking maybe I needed to include a `:key` attribute...

**Comment by robmadole** [comment]
Let me take a look at this. This is horrifying.

**Comment by robmadole** [comment]
Hmm. I removed the `:key` and I can't reproduce this. What browser?

**Comment by OriginalEXE** [comment]
Ok this is really weird, it works now for me as well, could swear it did not work yesterday.

Browser is Google Chrome, Version 63.0.3239.108 (Official Build) (64-bit)

**Comment by robmadole** [comment]
I hate these type of bugs! @ksherman I even tried with your ‘v-if’ style starting with “sort” and couldn’t reproduce. If you can create a test case for this I’ll fix it ASAP

**Comment by billti** [comment]
Funny, I hit the same issue migrating to FontAwesome 5 in React yesterday, so figured I'd try out Vue, and see this issue here!

See https://github.com/FortAwesome/Font-Awesome/issues/11967 for my comment on the (closed) React issue.

I tried to step through the code yesterday, and didn't get enough time to understand it fully, but could see in the `@fortawesome/fontawesome/index.es.js` code that the callback passed to `new MUTATION_OBSERVER` behaves quite differently with the way React re-renders the DOM, compared to just changing the class names on the `i`/`svg` element via a DOM event. I'd imagine it's the same cause here.

I ended up just drawing the two icons wrapped in divs, with the one I don't want being conditionally styled with `display: none`. (I also noticed I needed to move my `onClick` handler to the parent `div` also, as this appears to be lost with FontAwesome 5 if put directly on the `<i>`, which was working fine in Font Awesome 4).

**Comment by ksherman** [comment]
`This is horrifying.`  😂   I mean, we'll all survive! haha. Been out for the holiday weekend, I'll try and put together a reduced test and see what I can see!

**Comment by Reiss-Cashmore** [comment]
Experiencing the same, the :key stringify fix above works for me for now.

I can provide a sample from my project if you are still struggling to reproduce

In case this can help: My specific scenario is a little different but I'm pretty sure its the same issue. I load 6 chosen icons through a socket.io event so, the icons should change when this event fires to icons provided in the payload. (Well they should if this worked correctly) 

The weirdest part of all of this is that the icons get bound correctly to the set in the **first** socket.io event payload. The second newly received socket.io set updates the icons successfully also. However any other subsequent events updating the underlying property which is bound to my fontawesome icons seem to be ignored. I know the vue properties themselves are being updated with the data as I have verified with vue-devtools and by printing out the object in my html.

I don't want to rip out fa5 from my project and hopefully this :key fix doesn't let me down, would really like to see this addressed asap :(

If you need more info on the behaviour or help to reproduce then just ask.

**Comment by robmadole** [comment]
@Reiss-Cashmore yes if you can produce a test case that will help a ton.

@billti are you using `react-fontawesome`? From the comment you left in https://github.com/FortAwesome/Font-Awesome/issues/11967 it seems as though you are not.

**Comment by jsodeman** [comment]
I've got the same issue (see https://github.com/FortAwesome/Font-Awesome-Pro/issues/969). They :key fix didn't work for me, but using v-show does.

**Comment by jungleBadger** [comment]
I'm having the same behavior. Declaring icons like this wont work
```
<div v-if="tst">
			y
			<font-awesome-icon :icon="tst ? 'spinner' : 'rocket'" spin ></font-awesome-icon>
		</div>
		<div v-else>
			x
			<font-awesome-icon :icon="'rocket'" spin  ></font-awesome-icon>
		</div>
		<button  @click="x">x</button>
```
X and Y raw text got changed successfully but the icon rendered is the same (spinner one) on both if and else.

If I declare with :key property around the icons it work fine:
```
<div v-if="tst" :key="'x'">
			y
			<font-awesome-icon :icon="tst ? 'spinner' : 'rocket'" spin ></font-awesome-icon>
		</div>
		<div v-else :key="'y'">
			x
			<font-awesome-icon :icon="'rocket'" spin  ></font-awesome-icon>
		</div>
		<button  @click="x">x</button>
```

If I put the :key property on font-awesome-icon element wont work as well.


		"vue": "^2.5.13",
		"vue-fontawesome": "0.0.2",
		"vue-template-compiler": "^2.5.13",

**Comment by jungleBadger** [comment]
My mistake I guess. Using the wrong npm install.

from vue-fontawesome to @fontawesome/vue-fontawesome seems to work

**Comment by robmadole** [comment]
OK everyone. We uncovered a bug related to this that should be fixed now.

For all that were having trouble please upgrade to the latest version of `@fortawesome/fontawesome` and see if this fixes things up.

**Comment by ksherman** [comment]
@robmadole Thanks! Sorry I disappeared, we had a big launch in mid-Jan and I decided to push off migrating to FA5. But I'll be on it soon and report back! Thanks for your work on this :)

**Comment by robmadole** [comment]
No worries. If you run into problems we can reopen.

**Comment by CmdrSharp** [comment]
I'm having this exact issue still. I first noticed it without vue-fontawesome, which is why I made the switch thinking it'd solve it. Alas it did not.

`   "@fortawesome/fontawesome": "^1.1.4",
    "@fortawesome/fontawesome-free-brands": "^5.0.8",
    "@fortawesome/fontawesome-pro-light": "^5.0.8",
    "@fortawesome/fontawesome-pro-regular": "^5.0.8",
    "@fortawesome/fontawesome-pro-solid": "^5.0.8",
    "@fortawesome/vue-fontawesome": "0.0.22",
`

If I list five icons in a row, with different v-if's, the first one will be displayed whilst the others will not be rendered at all. No errors show in the JS console. Seems to work fine for anything not within either v-if or v-show statements.

Am I missing something, or is this still not fixed?

**Comment by CmdrSharp** [comment]
(forgot to tag @robmadole here - figured I shouldn't open a new issue if one already exists that has a lot more data)

**Comment by robmadole** [comment]
@CmdrSharp can you provide a reproducible test case? (codesandbox.io is a good tool)

**Comment by CmdrSharp** [comment]
@robmadole I've been trying to pretty much since I made that reply, but I have so far been unsuccessful. It's difficult to replicate the exact environment into a sandbox, hehe! I'll keep trying and let you know as soon as I know more.

**Comment by robmadole** [comment]
@CmdrSharp yes, I know that can be a challenge...

**Comment by CmdrSharp** [comment]
@robmadole Good news! I both re-produced it, and found a work-around.
It seems the shorthand exits for the font-awesome-icon causes this behavior. When closing that tag out normally instead, v-if cases behave like they should!

Example: https://codesandbox.io/s/y0ky64p1z

Not sure if I'm missing anything obvious here, but every single example from the repo readme shows using shorthand termination - so either the documentation should be updated, or this should work! :)

Hope it helps!

**Comment by robmadole** [comment]
Ok! I think I see what's going on. It is those self-closing tags. When you use them in a template like you've done they don't make it into browser like this:

<img width="305" alt="nesting" src="https://user-images.githubusercontent.com/132895/37491210-11d11468-286b-11e8-8f25-1ef61dd2769b.png">

We have a branch `upgrading-to-5.1.0` and I'll mention this issue there.

**Comment by Jakupov** [comment]
@robmadole 
Same issue appeared for me, but I don't have `<font-awesome-icon>` component, just only `<i></i>` which turns into svg when rendered.
package.json:
`"dependencies": {
        "@fortawesome/fontawesome": "^1.1.8",
        "@fortawesome/fontawesome-free-brands": "^5.0.13",
        "@fortawesome/fontawesome-pro-light": "^5.0.13",
        "@fortawesome/fontawesome-pro-regular": "^5.0.13",
        "@fortawesome/fontawesome-pro-solid": "^5.0.13",
        "@fortawesome/vue-fontawesome": "0.0.22",
        "bootstrap-vue": "^2.0.0-rc.11",
        "npm": "^6.0.1"
    }`
[There](https://stackoverflow.com/questions/49343425/vue-js-cant-toggle-a-font-awesome-icon) suggests to wrap it in span, but that does not work.
`<span v-if="role">
    <i class="fa fa-check"></i>
</span>
<span v-else>
    <i class="fa fa-times"></i>
</span>`
Anything else in span toggles correctly

**Comment by Jakupov** [comment]
Oww, I thought I was using it, because I have it in package.json and icons appeared successfully, only with <i>. Still new in modern js frameworks. Sorry for bothering then. Thanks for help.

**Comment by robmadole** [comment]
No worries. We need to do a better job with the docs!

**Comment by crtjr64** [comment]
My issue differs, I need to change the font when a data change has been made and returned from Ajax. I'm already in the dom, but can't change fontawesome now because its pure svg.. how do I toggle these?
